model_type: "logreg"   # or "3han"
model_path: "models/final_model.pt"
vocab_path: "models/vocab.pkl"
device: "cpu"
max_len: 100
fetch_web: true
num_evidence: 5
label_mapping:
  0: "Fake"
  1: "Real"


